plugins { id 'com.android.application' }
android {
    namespace 'com.dhruv.glaautologin'
    compileSdk 34
    defaultConfig {
        applicationId "com.dhruv.glaautologin"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes { release { minifyEnabled false } }
}
dependencies { implementation 'com.squareup.okhttp3:okhttp:4.12.0' }
